### PR TITLE
8.0 Updates

### PR DESCRIPTION
**Pull request by paul-griffith**

### CODE REVIEW

**Comment by kevinherron** [comment]
Is this ready to be squashed and merged into master, with master becoming the 8.0 examples?

**Comment by paul-griffith** [comment]
Yes, this should be good to go. All examples compile and passed my basic functional testing. The few deprecated examples are gone, and the naming conventions/package conventions are _much_ more consistent.

**Comment by lionelmazeyrat** [comment]
Hi @kevinherron, @paul-griffith,
In the dev/8.0, AbstractTagDriver is replaced by a new OPC-UA device.
A driver module based on AbstractTagDriver will need to be refactored for Ignition 8, or it will be compatible with Ignition 8 ?

**Comment by kevinherron** [comment]
@lionelmazeyrat `AbstractTagDriver` still exists. There may be some minor changes to make a driver based on it compile, but it's still there.

**Comment by lionelmazeyrat** [comment]
Thanks ! I'm eager to get my hands on this new exciting Ignition 8 and SDK

**Pull request merged**
